"""initial migration

Revision ID: 8afb09a1ad19
Revises: 
Create Date: 2025-05-21 16:34:02.306660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8afb09a1ad19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('event_datetime', sa.DateTime(), nullable=False),
    sa.Column('event_name', sa.String(length=256), nullable=True),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('event_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_client_id'), 'events', ['client_id'], unique=True)
    op.create_index(op.f('ix_events_event_datetime'), 'events', ['event_datetime'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_event_datetime'), table_name='events')
    op.drop_index(op.f('ix_events_client_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
