"""add r column + unique key

Revision ID: 9b9a0f85555c
Revises: 5fd69d76ca47
Create Date: 2025-08-19 09:54:26.629321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b9a0f85555c'
down_revision: Union[str, None] = '5fd69d76ca47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('sid', sa.String(length=64), nullable=False))
    op.add_column('events', sa.Column('r', sa.String(length=64), nullable=False))
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('events', 'r')
    op.drop_column('events', 'sid')
    # ### end Alembic commands ###
