"""update event_Datetime

Revision ID: d36b63a958d6
Revises: 8afb09a1ad19
Create Date: 2025-05-21 16:47:31.718048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd36b63a958d6'
down_revision: Union[str, None] = '8afb09a1ad19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'event_datetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_index('ix_events_event_datetime', table_name='events')
    op.create_index(op.f('ix_events_event_datetime'), 'events', ['event_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_event_datetime'), table_name='events')
    op.create_index('ix_events_event_datetime', 'events', ['event_datetime'], unique=True)
    op.alter_column('events', 'event_datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
