# global config
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 1m
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'fastapi'
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi-app:8000']

  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis-exporter:9121' ]

  - job_name: 'kafka'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]



